### ISSUE TITLE
Rofi theming suddenly broken

### ISSUE THREAD

**Issue by michaelBelsanti** [ntcarlson/dotfiles#5]
Today the script has suddenly stopped using the theming from the config.rasi file. Everything is now just white and black, I tried downloading the files and setting it up again to no avail. Did Rofi change how the configs work?

**Comment by ntcarlson** [comment]
Yep. Looks like Rofi 1.7.0 which released a couple of days ago made some changes to how the theming works. I just updated to 1.7.0 myself and am seeing the same behavior. I'll update this when I get a chance.

**Comment by ntcarlson** [comment]
Should be fixed now

**Comment by michaelBelsanti** [comment]
Yep, all good now, thanks!
